version: '3'

services:
  postgresql:
    image: postgres:14.5
    expose:
      - 5432:5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=syncbyte
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=syncbyte
    restart: always

  backend:
    image: minio/minio:latest
    expose:
      - 9000:9000
      - 9001:9001
    ports:
      - 9000:9000
      - 9001:9001
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    restart: always

  init-minio-bucket:
    image: minio/mc
    depends_on:
      - backend
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add local http://backend:9000 minioadmin minioadmin;
      /usr/bin/mc rm -r --force local/syncbyte-dev;
      /usr/bin/mc mb local/syncbyte-dev;
      /usr/bin/mc admin user add local accesskey123 secretkey123;
      /usr/bin/mc admin policy set local readwrite user=accesskey123;
      "

  agent:
    image: syncbyte:latest
    depends_on:
      - postgresql
      - backend
      - init-minio-bucket
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/local/bin/docker
    expose:
      - 50051:50051
    ports:
      - 50051:50051
    command:
      - agent
      - run

  engine:
    image: syncbyte:latest
    depends_on:
      - postgresql
      - backend
      - init-minio-bucket
    restart: on-failure
    expose:
      - 8000:8000
    ports:
      - 8000:8000
    command:
      - engine
      - run
