services:
  pg:
    image: "postgres:14.5"
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=syncbyte
      - POSTGRES_USER=syncbyte
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD","pg_isready","-q","-d","syncbyte","-U","syncbyte"]
      interval: 5s
      timeout: 5s
      retries: 5
  mongo:
    image: "mongo:4.4.18"
    ports:
      - "27017:27017"
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    restart: always
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
  agent:
    image: "syncbyte:latest"
    build: .
    ports:
      - "50051:50051"
    expose:
      - 50051
    volumes:
      - source_data:/mnt/data
      - app_data:/var/syncbyte/data
      - app_log:/var/syncbyte/log
    command: /usr/local/bin/syncbyte-agent run
  engine:
    image: "syncbyte:latest"
    build: .
    ports:
      - "50052:50052"
    expose:
      - 50052
    volumes:
      - app_log:/var/syncbyte/log
    command: /usr/local/bin/syncbyte-engine run -S
    depends_on:
      - pg
      - mongo
      - agent
volumes:
  mongo_data:
    driver: local
    driver_opts:
      type: none
      device: ./data/mongodata
      o: bind
  pg_data:
    driver: local
    driver_opts:
      type: none
      device: ./data/pgdata
      o: bind
  app_data:
    driver: local
    driver_opts:
      type: none
      device: ./data/appdata
      o: bind
  source_data:
    driver: local
    driver_opts:
      type: none
      device: ./data/sourcedata
      o: bind
  app_log:
    driver: local
    driver_opts:
      type: none
      device: ./data/applog
      o: bind
