services:
  pg:
    image: "postgres:14.5"
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=syncbyte
      - POSTGRES_USER=syncbyte
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD","pg_isready","-q","-d","syncbyte","-U","syncbyte"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    expose:
      - 6379
    restart: always
volumes:
  pg_data:
    driver: local
    driver_opts:
      type: none
      device: ./.testdata/pgdata
      o: bind
