"""2

Revision ID: 69af85c88076
Revises: 8c82bd31ef9a
Create Date: 2023-04-29 14:33:13.153646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69af85c88076'
down_revision = '8c82bd31ef9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_schedule',
    sa.Column('cron', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backup_schedule')
    # ### end Alembic commands ###
