apiVersion: v1
kind: ConfigMap
metadata:
  name: syncbyte-agent-configmap
data:
  agent.toml: |
    [core]
    grpc_addr = '0.0.0.0:50051'
    log_level = 'debug'
    log_path = '/var/syncbyte/log'

    [storage]
    nas_volume_mountpoint = '/var/syncbyte/data'
    type = 'nas'
